#ifndef CELLULOUNITY_GLOBAL_H
#define CELLULOUNITY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CELLULOUNITY_LIBRARY)
#  define CELLULOUNITYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CELLULOUNITYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CELLULOUNITY_GLOBAL_H
